### ISSUE TITLE
Not so much an issue as a fix for one.

### ISSUE THREAD

**Issue by grugsy** [WenXin20/BloomingBlocks#2]
I've tweaked the regions unexplored files a bit to improve the behavior.
![2024-01-06_19 22 04](https://github.com/WenXin20/BloomingBlocks/assets/6725027/a56e0ac8-5493-436d-9f41-d20c1f543b35)
[BB+ Regions Unexplored compat fix.zip](https://github.com/WenXin20/BloomingBlocks/files/13852157/BB%2B.Regions.Unexplored.compat.fix.zip)

**Comment by WenXin20** [comment]
Thanks, I'll try to take a look soon

**Comment by grugsy** [comment]
It was bugging me that those crystals weren't properly transparent, especially when using complementary shaders with euphoria patches... Shimmer and this pack were the only way I figured out how to get them to play nice with the shaders, with some minor adjustments of course. I believe I have the prismarite added to the shaders block properties as stained glass, but it may not be necessary. :)

**Comment by WenXin20** [comment]
Ah, I had made it non-transparent so that bloom would work for it

**Comment by grugsy** [comment]
That was confusing me, but somehow it ended up not needing to be and still working. I'm honestly not sure how I fiddled my way through it. It started as me trying to figure out how to make them cast reflections on water and realizing it's impossible with the way Euphoria patches renders transparency, and then I settled on just making them be transparent and glowy since they are meant to be a glass-like block as a "best I can do" type of thing.

**Comment by WenXin20** [comment]
Hmm, interesting

**Comment by grugsy** [comment]
Idk man,,, I just wanted them to not look so out of place when spawning next to other mod's crystals and colored lights. Thought I would share my results after a few days of mildly obsessing over it. I love my glowy stuff. lol
![2024-01-11_21 12 57](https://github.com/WenXin20/BloomingBlocks/assets/6725027/063ba593-c279-4eb3-85e2-e8b2696f3a86)

**Comment by WenXin20** [comment]
yeah, looks good
